### ISSUE TITLE
Can I have the dockerfile

### ISSUE THREAD

**Issue by xuesu** [library-testing/Muffin#6]
Dear Author,
I am deeply impressed by the quality of your paper. I am particularly interested in if your tool can still find bugs in Tensorflow 2.14. Therefore, I am wondering if it would be possible for you to share the Dockerfile of E1 so I can replicate your work on the latest version.

**Comment by library-testing** [comment]
Hi xuesu, thanks for your continued attention!

I am sorry that since it's been a long time, we can no longer find the Dockerfiles used to create the experimental environments.
Maybe you can find some useful information by viewing the layout of the image on the [DockerHub](https://hub.docker.com/layers/librarytesting/muffin/E1/images/sha256-d0f3ffcc0659e8429710197777993fffc150bb151f541ff0c738c2e68319f3cb?context=repo).

We apologize for any inconvenience caused.
@xuesu

**Comment by xuesu** [comment]
Thank you so much!
